---
    # Use apt module
  - name: Install docker.io
    apt:
      force_apt_get: yes
      name: docker.io
      state: present
    # Use apt module
  - name: Install pip
    apt:
      force_apt_get: yes
      name: python-pip
      state: present
    # Use pip module
  - name: Install Docker python module
    pip:
      name: docker
      state: present
    # Use command module
  - name: Increase virtual memory
    command: sysctl -w vm.max_map_count=262144
    # Use docker_container module
  - name: download and launch a docker elk container
    docker_container:
      name: elk
      image: sebp/elk
      state: started
      published_ports:
        - 5601:5601
        - 9200:9200
        - 5044:5044